linters:
  presets:
    - bugs
    - complexity
    - format
    - performance
    - style
    - unused
  disable:
    - wsl

linters-settings:
  nolintlint:
    allow-unused: false
    allow-leading-space: false
    require-explanation: true
    require-specific: true
