language: go

go:
  - stable
  - oldstable
  - master

before_install:
  - |
    (cd $GOPATH &&
    go get github.com/wadey/gocovmerge &&
    rm -rf $GOPATH/src/github.com/wady)

before_script:
  - mkdir COVERAGE

script:
  - |
    COVERAGE_DIR=COVERAGE/MODULE \
    go test -v -coverprofile=COVERAGE/root.module ./...

  - |
    COVERAGE_DIR=COVERAGE/GOPATH \
    ./run_in_temp_gopath_with_go_modules_disabled \
    go test -v -coverprofile=COVERAGE/root.gopath ./...

  - go tool cover -func <(gocovmerge $(find COVERAGE -type f))
