name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 14 * * MON"

jobs:
  test:
    name: Test and report coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.x

      - name: Run tests in module-aware mode
        env:
          COVERAGE_DIR: COVERAGE_MODULE_MODE
        run: |
          go test \
            -coverprofile="coverage.main.module-mode" \
            -race \
            -v \
            ./...

      - name: Run tests in GOPATH mode
        env:
          COVERAGE_DIR: COVERAGE_GOPATH_MODE
        run: |
          ./run_in_temp_gopath_with_go_modules_disabled \
          go test \
            -coverprofile="coverage.main.gopath-mode" \
            -race \
            -v \
            ./...

      - name: Merge coverage profiles
        run: |
          (cd "$GOPATH" && go get github.com/wadey/gocovmerge)
          rm -rf "$GOPATH/src/github.com/wadey"
          gocovmerge \
            "coverage.main.module-mode" \
            $(find "COVERAGE_MODULE_MODE" -type f) \
                   ".TEMP_GOPATH/src/github.com/bloomberg/docket/coverage.main.gopath-mode" \
            $(find ".TEMP_GOPATH/src/github.com/bloomberg/docket/COVERAGE_GOPATH_MODE" -type f) \
            > coverage.out

      - name: Show per-function coverage profile
        run: go tool cover -func=coverage.out

      - name: Convert coverage profile to lcov format
        uses: jandelgado/gcov2lcov-action@v1.0.9
        with:
          infile: coverage.out
          outfile: coverage.lcov

      - name: Report to Coveralls
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.x

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Prettier
        uses: creyD/prettier_action@v4.3
        with:
          dry: true
          prettier_options: --check .

  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run ShellCheck
        uses: bewuethr/shellcheck-action@v2
